package chap15_exception;

public class _02_TryCatchFinally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] intArr = new int[3];
		String[] strArr = new String[3];
		
		int idx = 0;
		
		// 1. try ~ catch ~ finally
		// try 블록에 실행될 코드를 작성하고 try 블록에 작성된 코드에서 에러가 발생하면
		// catch 블록으로 이동해서 예외처리를 한다.
	}

}
